import type { Metadata } from "next";
import ReactQueryProvider from "@/providers/react-query-provider";
import "./globals.css";


export const metadata: Metadata = {
  title: "WELCOME TO NEXT.JS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr">
      <body>
        <ReactQueryProvider>
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}